/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package com.ricm3.packnight.model.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ETAT = 6;
  /** RegularExpression Id. */
  int TRANSITION = 7;
  /** RegularExpression Id. */
  int ETATSUIVANT = 8;
  /** RegularExpression Id. */
  int ENTREE = 9;
  /** RegularExpression Id. */
  int SORTIE = 10;
  /** RegularExpression Id. */
  int ETAT_INITIAL = 11;
  /** RegularExpression Id. */
  int ETAT_FINAL = 12;
  /** RegularExpression Id. */
  int ETAT_BLOQUANT = 13;
  /** RegularExpression Id. */
  int AUTOMATE = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int SYMBOL = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"=\"",
    "\"Etat\"",
    "\"Transition\"",
    "\"ETATSUIVANT\"",
    "\"ENTREE\"",
    "\"SORTIE\"",
    "\"ETAT_INITIAL\"",
    "\"ETAT_FINAL\"",
    "\"ETAT_BLOQUANT\"",
    "\"AUTOMATE\"",
    "<STRING>",
    "<LETTER>",
    "<DIGIT>",
    "<SYMBOL>",
  };

}
